Yapay Zeka Projesi Arayüzü/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Yapay_Zeka_Projesi_Arayüzü.Controllers
{
    public class AdminLayoutController : Controller
    {
        // GET: AdminLayout
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult AdminSpinner()
        {
            return PartialView();
        }

        public PartialViewResult AdminSideBar()
        {
            return PartialView();
        }




        
        
    }
}

Yapay Zeka Projesi Arayüzü/Views/AdminLayout/AdminSideBar.cshtml
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-secondary navbar-dark">
        <a href="#" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Admin Paneli
            </h3>
        </a>
        <div class="navbar-nav w-100">
            <div class="nav-item dropdown">
                
                <div class="dropdown-menu bg-transparent border-0">
                    <a href="button.html" class="dropdown-item">Buttons</a>
                    <a href="typography.html" class="dropdown-item">Typography</a>
                    <a href="element.html" class="dropdown-item">Other Elements</a>
                </div>
            </div>
            <a href="/UILayout/Index" target="_blank" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Siteye Git</a>
            <a href="/Anasayfa/Index" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Anasayfa</a>
            <a href="/Hizmetler/Index" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Hizmetler</a>
            <a href="/Ornekler/Index" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Örnekler</a><a href="/Login/End/" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Çıkış Yap</a>
        </div>
    </nav>
</div>

Yapay Zeka Projesi Arayüzü/Views/AdminLayout/AdminSpinner.cshtml
<div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

Yapay Zeka Projesi Arayüzü/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Yapay Zeka Projesi Admin Tarafı</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/Templates/agency/assets/img/Admin Settings Male.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/Templates/darkpan-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/Templates/darkpan-1.0.0/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Templates/darkpan-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/Templates/darkpan-1.0.0/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        @Html.Action("AdminSpinner", "AdminLayout")
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        @Html.Action("AdminSideBar", "AdminLayout")
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>


                <div class="navbar-nav align-items-center ms-auto">
                    
                    <div class="nav-item dropdown">
                        Designed and Developed by Emir Alp Esmergül
                    </div>
                    
                </div>
            </nav>
            <!-- Navbar End -->
            <!-- Blank Start -->
            @RenderBody()
            <!-- Blank End -->
            <!-- Footer Start -->
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
       
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/chart/chart.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/easing/easing.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/waypoints/waypoints.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/Templates/darkpan-1.0.0/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/Templates/darkpan-1.0.0/js/main.js"></script>
</body>

</html>